CC = gcc
CFLAGS = -Wall

SCRS_CLIENT = HTTP_Client.c
SCRS_SERVER = HTTP_Server.c

OBJS_CLIENT = $(SCRS_CLIENT:.c=.o)
OBJS_SERVER = $(SCRS_SERVER:.c=.o)

TARGET_CLIENT = HTTP_Client
TARGET_SERVER = HTTP_Server

all: $(TARGET_CLIENT) $(TARGET_SERVER)

$(TARGET_CLIENT): $(OBJS_CLIENT)
	$(CC) $(CFLAGS) $(OBJS_CLIENT) -o $(TARGET_CLIENT)

$(TARGET_SERVER): $(OBJS_SERVER)
	$(CC) $(CFLAGS) $(OBJS_SERVER) -o $(TARGET_SERVER)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS_CLIENT) $(OBJS_SERVER) $(TARGET_CLIENT) $(TARGET_SERVER)
